# Generated by Django 4.1.4 on 2023-02-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=50)),
                ('amount', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='', max_length=50)),
                ('age', models.CharField(default='', max_length=50)),
                ('weight', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
